language: perl
sudo: false
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
before_install:
  - curl https://gist.githubusercontent.com/ts-3156/fe3328ecbfb096b166f1643fb369ad05/raw/63b9d55bbfbabe876fe4849601946d2bba33f8c8/mecab_install.sh | bash
